language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: cafe3cc5-fc69-4588-b8f3-bece79803bfd
  app: hw3cicd06
  on:
    repo: Thinh545/06_HW3_CICD
notifications:
  slack: hcmusglobal:ereBPoRZEJXeA7FoMV1icBA3
    on_success: always
    on_failure: always
