language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: UdK8XvY6QSfAi0hRX7HyGQtROXjFjWLNIgbY6JBuOI+zxqSuR3WTcBQxdxEKOxTEleh1MNF4994avNz2qXqkZPW8GnKIYO1rztCh7q0r11uJj2tq4DwN0VuhW5zBYYneBR9TUDNHcpEyT2/3H0aIGezEqM8DY3DPXtagx9ywqHNmjXg9bp/7Md7xEvhFycY83Q5V7X+Y6EIeTxi//LdUd4XVE3da2msp2MC4z8k/BlAfF7TKZeT/lasr444x4SBMSb7jwd4k+y+gr13xx9BbddD/zHuFE09PiURaztLX9g5Xuhu/DsxU1itkVxytPZSRCTFGksVvoDcIyJibD+ukjroRfHBErT9i78B7jNyBwMjU50i19EbuPcqKddLzj37OpbDl+RJVozEk/a4JI68gvj/PmVCAUhA3dWrKXvluhcsyLKcELh8UyA5od33f8MAtZnMaJvML/NYpkO73VVpsIYq3+fKuwU1TXXRWOqujCI2pqibBXz8XF+e370fPT+zQ7ZjWiuLAejrVpTke8/75BxLXUbW1KHsUK9CyFzT94IfxuDfEPjutvEsROjNCwDhWkd9YBrUTGWGyfXZKqaoxVpN4XqVqzs081flX1x8XtV1rpp7HKnVvZPvZv+7VUkUUZVFvCfjsZhBJJWabFjaS9+tLiGeCzkz9Hr1/N72I+qs=
  app: hw3cicd06
