language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
deploy:
  provider: heroku
  api_key: 
    secure: SkvFUamEVVfPLk8Tpl56FF0P3PfMkTu3d4B9n2uKjMmJK+ce8eXykPqOac+VMBhAARA6BvD+V2WUKLyA4fyF7uXO7/7drXUq+/iTvytO7IEK5pYVxTyl7cfvGb7PysTmHnXTZCJfQyOJeQolShXmqxOQN8bUWniEoKqfc3F638qklnct9Eu+HXTK/fuB/W/tmEk4ltg/g56UvVLCpgPb6HAm6zjaGa6I0oq+/PO4uhpNGXjcG9RrsAg4tsfaqrPFnThrb8c3rXOCaFW/6vPFUynJqW42X8AVKBsFyLWRi0l7BST/Ek1VBceLloId5nmoNOQcQpD6aDS9LbSKgqN0cnFKUBGhXT27/H27NJ37niTW7VsOHcANnENfiCxBBNrm5IrQ+yvdijMjvng9zBeWr0LFaa8Xpf9AHC0+0b87GmKeNWQQSt0xiKgvCl/1g91fX8zoxslZFc3rPabGcCRwKh7/7Q4ZbbDzrYLXzlmZnponbDcGExJvuruaIdXJ7TUNjj7bIiINLZEAFuq05ZvI9oamy3qIeXktU5eJVq7hUiTH7DQBKBV+DScOIHnH8A6GhH71btMjplTDkolRa9vqHBS33dOfYPUcIYd5NsUWs43JyCnL4sRzm1Ftsmp4TRWaTUHFNoYBup+9rZWEu7wrxEebnZmLOe51U9DQNOyxS6g=
  app: hw3cicd06
  on:
    branch: master